### ISSUE TITLE
Develop chatbot prototype in C# and ASP.NET Core

### ISSUE THREAD

**Issue by JHuggins11** [JHuggins11/CO659-TeamApp#12]
Prototype for the chatbot developed in C# and ASP.NET Core.

**Comment by isabellethorpe** [comment]
Think it's safe to say we can close this as the chatbot is not feasible? @hsadiq32 @JHuggins11

**Comment by JHuggins11** [comment]
Sorry I got to this late. Yes, this will be closed and will be made as another task to develop a general prototype with the whole team.
